export type ReportsSummaryDto = {
  companies: number;
  users: number;
  employees: number;
  workLocations: number;
  shifts: number;
  planningPeriods: number;
  publishedPlanningPeriods: number;
  timeEntries: number;
  vacationsPending: number;
  permissionsPending: number;
  incidentsOpen: number;
  activeSessions: number;
  currentMonthFrom: string;
  currentMonthTo: string;
  currentMonthPlannedMinutes: number;
  currentMonthWorkedMinutes: number;
  currentMonthCoverageRate: number;
  currentMonthAbsenceDays: number;
  currentMonthIncidentDays: number;
  currentMonthUnplannedDays: number;
};
